### ISSUE TITLE
unable to load image

### ISSUE THREAD

**Issue by cptn-cosmo** [DiamondPrecisionComputing/unraid-templates#11]
I am constantly getting this error message in the logs, but I am not sure where it is coming from

`ddns-updater: Could not download icon https://github.com/DiamondPrecisionComputing/unraid-templates/blob/main/templates/img/ddnsgopher.png?raw=true`

**Comment by DiamondPrecisionComputing** [comment]
This issue was fixed in a previous release. Have you updated the app recently?

**Comment by cptn-cosmo** [comment]
I am not sure how to see the current version number, however there was an update of the docker container today which I installed. As a suggestion, it would be nice if the current version would be shown in the web interface :)
